name: manage_center
description: "ACSP MUPIT"
publish_to: 'none'

version: 1.0.2+15

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  go_router: ^17.1.0
  bloc: ^9.2.0
  http: ^1.1.0
  shared_preferences: ^2.5.3
  provider: ^6.0.5
  intl: ^0.20.2
  fl_chart: ^1.1.1
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  local_auth: ^3.0.0
  flutter_colorpicker: ^1.1.0
  package_info_plus: ^9.0.0
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter_local_notifications: ^20.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - lib/assets/icon/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "lib/assets/icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/assets/icon/icon.png"